# Generated by Django 5.0.2 on 2024-03-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, null=True, verbose_name='ID сессии платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Не оплачен', 'Unpaid'), ('Оплачен', 'Paid')], default='Не оплачен', verbose_name='Статус платежа'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_url',
            field=models.TextField(blank=True, null=True, verbose_name='URL платежа'),
        ),
    ]
