# Generated by Django 5.0.2 on 2024-03-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pay_id',
            field=models.CharField(blank=True, null=True, verbose_name='ID для платежей'),
        ),
    ]
