# Generated by Django 5.0.2 on 2024-03-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Последнее обновление'),
        ),
    ]
